"""RA configuration — loaded from env vars (ACME_RA_*) and/or a config file.

No real secrets or work-domain identifiers in committed files.
All values use placeholders (CA01, WORK-DOMAIN.local, etc.).
"""

from __future__ import annotations

from pathlib import Path
from typing import Literal

from pydantic import BaseModel, Field, SecretStr, field_validator, model_validator
from pydantic_settings import BaseSettings, SettingsConfigDict

from acme_adcs_ra.jws import _base64url_decode
from acme_adcs_ra.policy import validate_dns_name

# Credential strength floors (see RAConfig._credentials_are_strong).
#
# An EAB MAC key is the *only* thing standing between a network-reachable peer
# and an account that can order certificates from the CA; an admin token guards
# the maintenance surface. Both are generated by `scripts/eab.py` as
# ``secrets.token_urlsafe(32)`` — 32 random bytes, 43 base64url characters — so
# these floors accept every credential the shipped tooling produces and reject
# hand-typed ones.
MIN_EAB_MAC_KEY_BYTES = 32
MIN_ADMIN_TOKEN_CHARS = 32


class EABEntry(BaseModel):
    """One EAB credential mapping kid → MAC key (base64url)."""

    kid: str
    mac_key: SecretStr


class SANScope(BaseModel):
    """DNS SAN patterns allowed for a given account (EAB kid).

    Patterns support exact-match domain names and leftmost-label wildcards
    (``*.example.com``). Wildcard semantics follow RFC 4592: ``*.example.com``
    matches ``foo.example.com`` but not ``a.b.example.com``.
    """

    dns_patterns: list[str] = []

    @field_validator("dns_patterns")
    @classmethod
    def _validate_dns_patterns(cls, v: list[str]) -> list[str]:
        for p in v:
            if "*" in p:
                if not (p.startswith("*.") and "*" not in p[2:] and p[2:]):
                    raise ValueError(
                        f"invalid DNS pattern {p!r}: only leftmost-label wildcards "
                        f"(*.example.com) are supported"
                    )
                domain = p[2:]
            else:
                domain = p
            try:
                validate_dns_name(domain)
            except ValueError as exc:
                raise ValueError(
                    f"invalid DNS pattern {p!r}: {exc}"
                ) from exc
        return v


class RAConfig(BaseSettings):
    """Top-level RA settings. Loads from env vars prefixed ACME_RA_*."""

    model_config = SettingsConfigDict(
        env_prefix="ACME_RA_",
        env_nested_delimiter="__",
        # Allow a .env file next to the config or specified via ACME_RA_CONFIG_PATH
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )

    # --- EAB allowlist -------------------------------------------------------
    eab_allowlist: list[EABEntry] = []

    # --- ADCS target (placeholders only) -------------------------------------
    adcs_host: str = "CA01.WORK-DOMAIN.local"
    adcs_template: str = "ACME-ServerAuth"
    adcs_ca_name: str = "CONTOSO-CA01-CA"
    # Optional PEM bundle to verify the ADCS /certsrv/ TLS cert (private CA).
    # None/blank -> OS trust store (the gMSA host's local roots).
    adcs_ca_bundle: str | None = None
    # WI-020: assumed CA Web Enrollment UI locale. "en" (default) enables
    # English-string disposition heuristics. A non-"en" locale suppresses
    # those heuristics and relies on locale-independent signals (ReqID,
    # certnew.cer URL) only — failing loudly if none match.
    adcs_locale: str = "en"

    # --- ACME server surface -------------------------------------------------
    base_url: str = "http://localhost:8000"
    terms_of_service: str = ""

    # --- TLS termination (optional) ------------------------------------------
    # When both are set, uvicorn terminates TLS directly. This is the
    # scheduled-task / gMSA deployment shape, where there is no IIS reverse
    # proxy in front. Leave both unset to serve plain HTTP (loopback-only lab
    # use, e.g. the enrollment spike with a local client).
    tls_certfile: Path | None = None
    tls_keyfile: Path | None = None

    # --- Bind address (decoupled from base_url for reverse-proxy hosting) -----
    # Behind IIS/HttpPlatformHandler (or any reverse proxy) the app binds to a
    # loopback port the proxy assigns, while base_url stays the PUBLIC URL used
    # to construct ACME directory / JWS-bound URLs. Empty/None => derive from
    # base_url (direct-serve / loopback lab use).
    bind_host: str = ""
    bind_port: int | None = None
    # When fronted by a TLS-terminating reverse proxy, trust its forwarded
    # headers so the JWS full-URL binding (threat-model §4.D) sees the public
    # scheme/host. forwarded_allow_ips bounds which proxy IPs may set them.
    trust_proxy: bool = False
    forwarded_allow_ips: str = "127.0.0.1"

    # --- SAN scope per account (kid → allowed DNS glob patterns) -------------
    san_scopes: dict[str, SANScope] = {}

    # --- Storage -------------------------------------------------------------
    db_path: Path = Path("acme_ra.db")
    # ACME order/authz lifetime (RFC 8555 §7.1.4). Orders must not be born
    # expired or well-behaved clients reject them immediately.
    order_expiry_seconds: int = 3600

    # --- DoS caps (threat-model §4.G) ----------------------------------------
    # Maximum identifiers per order (bounds per-request work and DB growth)
    # In this implementation, 1 identifier = 1 authorization, so this caps both.
    max_identifiers_per_order: int = 50
    # Maximum CSR body size in bytes (bounds memory + parsing work)
    max_csr_size_bytes: int = 8192
    # Maximum complete flattened-JWS request body.  This is enforced while
    # streaming, before JSON/base64 decoding, so an unauthenticated peer cannot
    # make the worker buffer an arbitrarily large body.
    max_jws_body_size_bytes: int = 65536

    # --- In-app rate limiting (WI-016) --------------------------------------
    # Per-account (per-kid) order creation ceiling per rolling window.
    # 0 = disabled (rely on reverse-proxy only). Defense-in-depth: bounds a
    # leaked EAB credential's cert flood even without a correctly-configured
    # reverse proxy.
    rate_limit_orders_per_window: int = 50
    # Rolling window duration in seconds.
    rate_limit_window_seconds: int = 3600
    # Global backstop: max orders across ALL accounts per window. 0 = disabled.
    rate_limit_global_per_window: int = 0
    # Per-kid overrides: {kid: limit}. If a kid is not listed, the default
    # rate_limit_orders_per_window applies.
    rate_limit_overrides: dict[str, int] = {}

    # --- Unauthenticated nonce ceiling ---------------------------------------
    # /acme/new-nonce is unauthenticated and each call is a SQLite write, so a
    # flood contends for the single writer with the issuance path. This is an
    # in-process token bucket applied BEFORE the write. 0 = disabled (rely on
    # the reverse proxy only). Defaults are far above any legitimate ACME
    # client's needs: a renewal issues a handful of nonces, not hundreds.
    nonce_rate_limit_per_second: float = 20.0
    nonce_rate_limit_burst: int = 100

    # --- Audit durability ----------------------------------------------------
    # The default jsonl sink writes next to the database, so a host compromise
    # — the adversary the threat model calls load-bearing (§4.A) — destroys the
    # audit table and its only mirror together. Set this in production to
    # refuse startup unless audit events leave the box (syslog or HEC).
    audit_offbox_required: bool = False

    # --- SIEM / audit emission -----------------------------------------------
    # Auditing every issuance is mandatory (hard rule). There is no toggle.
    # The default sink is JSON-lines next to the database; syslog and Splunk
    # HEC are optional operator-configured targets.
    siem_sink: Literal["jsonl", "syslog", "hec"] = "jsonl"
    siem_jsonl_path: Path | None = None
    siem_syslog_host: str = ""
    siem_syslog_port: int = 514
    siem_syslog_proto: Literal["udp", "tcp"] = "udp"
    siem_hec_url: str = ""
    siem_hec_token: SecretStr = Field(default_factory=lambda: SecretStr(""))
    siem_hec_index: str = ""
    siem_hec_sourcetype: str = "acme-adcs-ra"
    # Bound the in-memory HEC delivery queue. A slow or unreachable HEC
    # endpoint must not let request-driven audit events accumulate without
    # limit on an issuance-path host; beyond this depth events are dropped
    # from the HEC sink (never from the local audit table) and counted.
    # Must be >= 1. At 0 or below, `_hec_inflight >= hec_queue_max` is already
    # true at startup with nothing in flight, so EVERY event is dropped — while
    # the emitter still reports itself enabled, so the audit_offbox_required
    # gate passes and the operator believes events are leaving the host. That
    # is the exact failure the gate was added to prevent, reachable by a typo.
    siem_hec_queue_max: int = Field(default=1000, ge=1)

    # Admin API token for maintenance endpoints (e.g., nonce cleanup)
    admin_token: SecretStr = Field(default_factory=lambda: SecretStr(""))

    # Refuse to reclaim an order that may still be enrolling. The reclaim
    # endpoint's only machine check is "no certificate row", which is also true
    # mid-flight, so reclaiming a live enrollment causes double issuance. The
    # default is twice the enrollment leg's own 30s timeout: past that, an
    # enrollment cannot still be in progress.
    reclaim_minimum_processing_age_seconds: int = 60

    # --- CA-side revocation confirmation (WI-024 callback) -------------------
    # Confirming that the CA actually revoked a serial is a *different*
    # authority from general maintenance: it asserts an external security event
    # the RA cannot see. Sharing the maintenance token meant any token holder
    # could drop a still-valid certificate off the retry queue and write a
    # success audit for a revocation that never happened. The confirm endpoint
    # therefore requires this dedicated credential and refuses the admin token;
    # with it unset the endpoint is disabled (fail closed).
    revocation_confirm_token: SecretStr = Field(default_factory=lambda: SecretStr(""))
    # Optional independent proof. The RA holds no CA rights, but a CRL is
    # published, signed by the CA, and readable by anyone — so fetching it is
    # the one check available to the RA that does NOT depend on the calling
    # agent's honesty. When set, a confirmation is verified against the CRL
    # and the audit records `verification="crl-verified"` rather than
    # `"agent-asserted"`.
    revocation_confirm_crl_url: str = ""
    # Fail closed: refuse to confirm at all unless the CRL proves the serial is
    # revoked. Requires revocation_confirm_crl_url.
    revocation_confirm_require_crl_evidence: bool = False
    # Bound the CRL fetch so a slow/hostile endpoint cannot pin a worker.
    revocation_confirm_crl_timeout_seconds: float = 10.0
    revocation_confirm_crl_max_bytes: int = 10 * 1024 * 1024
    # An absolute ceiling on how stale a CRL the RA will act on. A signed CRL
    # never stops verifying, and `nextUpdate` is chosen by the CA, so neither
    # bounds replay of a pre-revocation view on its own.
    revocation_confirm_crl_max_age_seconds: int = 7 * 24 * 3600

    # --- Credential strength -------------------------------------------------
    # EAB MAC keys and the admin token had no strength validation at all: a
    # one-character admin token was accepted, and an EAB entry whose mac_key
    # decoded to zero bytes was treated as a *present* key — so anyone who knew
    # the kid could forge the binding with an empty HMAC key. Both are enforced
    # at config load, which is the only place that sees them before they become
    # load-bearing. Set this to True ONLY for a lab or CI fixture; production
    # deployments must leave it False.
    allow_weak_credentials: bool = False

    # --- Legacy unauthenticated resource reads --------------------------------
    # RFC 8555 §7.4.2 specifies POST-as-GET for the certificate and
    # authorization; both POST forms exist and are account-scoped. The plain
    # GET forms were retained for client compatibility, and were documented as
    # "not an existence oracle because the URL is unguessable" — but they are
    # more than that: they answer for a certificate whose *account* has been
    # deactivated, or whose EAB kid has been pulled from the allowlist. Kid
    # eviction is meant to be a complete eviction, re-checked on every
    # authenticated request; a URL held from before the eviction still reads
    # through the GET form, bypassing that eviction.
    #
    # Defaulted False (2026-08-15 review, finding 4): secure by default, in
    # line with this project's usual preference for the stricter default. The
    # RA's own POST-as-GET path is proven to complete a full order→certificate
    # flow with this off (see the security-review regression tests), so the
    # only compatibility question is client-side. The legacy GET code path is
    # retained but gated: set this True to re-enable it for a client that is
    # known NOT to support POST-as-GET. The pending lab re-proof now validates
    # the secure (default-off) configuration; if Certify the Web is confirmed
    # to use POST-as-GET, the legacy GET forms should be removed entirely.
    allow_unauthenticated_resource_get: bool = False

    @model_validator(mode="after")
    def _no_duplicate_eab_kids(self) -> RAConfig:
        """Duplicate kids would silently overwrite EAB credentials — reject them."""
        seen: set[str] = set()
        for entry in self.eab_allowlist:
            if entry.kid in seen:
                raise ValueError(f"duplicate EAB kid: {entry.kid}")
            seen.add(entry.kid)
        return self

    @model_validator(mode="after")
    def _credentials_are_strong(self) -> RAConfig:
        """Reject empty/short EAB MAC keys and admin tokens at load time.

        Fails closed and loudly at startup rather than silently accepting a
        credential that cannot carry the authentication weight placed on it.
        """
        if self.allow_weak_credentials:
            return self

        problems: list[str] = []

        for entry in self.eab_allowlist:
            kid = entry.kid
            if not kid.strip() or kid != kid.strip():
                problems.append(
                    f"EAB kid {kid!r} must be non-empty and free of surrounding whitespace"
                )
            try:
                key_bytes = _base64url_decode(entry.mac_key.get_secret_value())
            except ValueError:
                # binascii.Error (bad padding/alphabet) and the non-ASCII
                # ValueError both subclass ValueError.
                problems.append(f"EAB mac_key for kid {kid!r} is not valid base64url")
                continue
            if len(key_bytes) < MIN_EAB_MAC_KEY_BYTES:
                problems.append(
                    f"EAB mac_key for kid {kid!r} decodes to {len(key_bytes)} bytes; "
                    f"at least {MIN_EAB_MAC_KEY_BYTES} are required "
                    f"(generate one with `python scripts/eab.py new`)"
                )

        admin_token = self.admin_token.get_secret_value()
        if admin_token and len(admin_token) < MIN_ADMIN_TOKEN_CHARS:
            problems.append(
                f"admin_token is {len(admin_token)} characters; at least "
                f"{MIN_ADMIN_TOKEN_CHARS} are required"
            )

        confirm_token = self.revocation_confirm_token.get_secret_value()
        if confirm_token and len(confirm_token) < MIN_ADMIN_TOKEN_CHARS:
            problems.append(
                f"revocation_confirm_token is {len(confirm_token)} characters; at "
                f"least {MIN_ADMIN_TOKEN_CHARS} are required"
            )

        # Separating the confirm authority is the whole point of having a
        # second credential: the sync agent needs to confirm revocations, and
        # must NOT thereby hold the maintenance authority that can reclaim a
        # processing order or drain the nonce table. Setting both to the same
        # string silently collapses that separation back into one credential
        # while every individual check still passes.
        if admin_token and confirm_token and admin_token == confirm_token:
            problems.append(
                "admin_token and revocation_confirm_token are identical, which "
                "defeats the separation they exist to create — the revocation "
                "agent would hold full maintenance authority. Generate a "
                "distinct confirm token"
            )

        if problems:
            raise ValueError(
                "weak credentials rejected at startup: "
                + "; ".join(problems)
                + ". Set allow_weak_credentials=true ONLY for a lab or CI fixture."
            )
        return self

    @model_validator(mode="after")
    def _offbox_audit_when_required(self) -> RAConfig:
        """Fail startup, loudly, rather than audit only to the box being attacked.

        This is opt-in (``audit_offbox_required``) so lab and CI keep the
        zero-config jsonl sink, but once an operator sets it the RA will not
        start in a posture where the audit trail dies with the host.
        """
        if self.audit_offbox_required and self.siem_sink not in ("syslog", "hec"):
            raise ValueError(
                "audit_offbox_required is set, but siem_sink is "
                f"{self.siem_sink!r}: the jsonl sink writes to the RA host "
                "itself, so a host compromise takes the audit trail with it. "
                "Configure the syslog or hec sink."
            )
        return self

    @model_validator(mode="after")
    def _crl_evidence_is_obtainable(self) -> RAConfig:
        """Requiring CRL evidence without a CRL URL would wedge every confirm."""
        if (
            self.revocation_confirm_require_crl_evidence
            and not self.revocation_confirm_crl_url
        ):
            raise ValueError(
                "revocation_confirm_require_crl_evidence is set but "
                "revocation_confirm_crl_url is empty: the RA would have no way "
                "to obtain the evidence it is required to check."
            )
        return self

    @model_validator(mode="after")
    def _tls_cert_key_paired(self) -> RAConfig:
        """TLS needs both halves or neither — a lone cert/key is a misconfig
        that would silently fall back to plain HTTP."""
        if bool(self.tls_certfile) != bool(self.tls_keyfile):
            raise ValueError("tls_certfile and tls_keyfile must be set together")
        return self

    def eab_keys_by_kid(self) -> dict[str, str]:
        """Return {kid: mac_key} for fast EAB lookup.

        The mac_key value is the base64url-encoded key as stored in config.
        Use ``eab_key_bytes`` when the raw key bytes are needed (e.g. HMAC).
        """
        return {e.kid: e.mac_key.get_secret_value() for e in self.eab_allowlist}

    def eab_key_bytes(self, kid: str) -> bytes | None:
        """Return the decoded EAB MAC key bytes for a kid, or None if unknown."""
        for entry in self.eab_allowlist:
            if entry.kid == kid:
                return _base64url_decode(entry.mac_key.get_secret_value())
        return None
