"""RA configuration — loaded from env vars (ACME_RA_*) and/or a config file.

No real secrets or work-domain identifiers in committed files.
All values use placeholders (CA01, WORK-DOMAIN.local, etc.).
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Literal
from urllib.parse import urlsplit

from pydantic import BaseModel, Field, SecretStr, field_validator, model_validator
from pydantic_settings import BaseSettings, SettingsConfigDict

from acme_adcs_ra.jws import _base64url_decode
from acme_adcs_ra.policy import validate_dns_name

# Credential strength floors (see RAConfig._credentials_are_strong).
#
# An EAB MAC key is the *only* thing standing between a network-reachable peer
# and an account that can order certificates from the CA; an admin token guards
# the maintenance surface. Both are generated by `scripts/eab.py` as
# ``secrets.token_urlsafe(32)`` — 32 random bytes, 43 base64url characters — so
# these floors accept every credential the shipped tooling produces and reject
# hand-typed ones.
MIN_EAB_MAC_KEY_BYTES = 32
MIN_ADMIN_TOKEN_CHARS = 32


logger = logging.getLogger("acme_adcs_ra.config")


class EABEntry(BaseModel):
    """One EAB credential mapping kid → MAC key (base64url)."""

    kid: str
    mac_key: SecretStr


class SANScope(BaseModel):
    """DNS SAN patterns allowed for a given account (EAB kid).

    Patterns support exact-match domain names and leftmost-label wildcards
    (``*.example.com``). Wildcard semantics follow RFC 4592: ``*.example.com``
    matches ``foo.example.com`` but not ``a.b.example.com``.
    """

    dns_patterns: list[str] = []

    @field_validator("dns_patterns")
    @classmethod
    def _validate_dns_patterns(cls, v: list[str]) -> list[str]:
        for p in v:
            if "*" in p:
                if not (p.startswith("*.") and "*" not in p[2:] and p[2:]):
                    raise ValueError(
                        f"invalid DNS pattern {p!r}: only leftmost-label wildcards "
                        f"(*.example.com) are supported"
                    )
                domain = p[2:]
            else:
                domain = p
            try:
                validate_dns_name(domain)
            except ValueError as exc:
                raise ValueError(
                    f"invalid DNS pattern {p!r}: {exc}"
                ) from exc
        return v


class RAConfig(BaseSettings):
    """Top-level RA settings. Loads from env vars prefixed ACME_RA_*."""

    model_config = SettingsConfigDict(
        env_prefix="ACME_RA_",
        env_nested_delimiter="__",
        # Allow a .env file next to the config or specified via ACME_RA_CONFIG_PATH
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )

    # --- EAB allowlist -------------------------------------------------------
    eab_allowlist: list[EABEntry] = []
    # Lifetime cap on durable ACME accounts created under one EAB kid. The
    # store counts every account row, including deactivated accounts, so a
    # client cannot recycle durable capacity by deactivating an account.
    max_accounts_per_eab_kid: int = Field(default=1, ge=1)

    # --- ADCS target (placeholders only) -------------------------------------
    adcs_host: str = "CA01.WORK-DOMAIN.local"
    adcs_template: str = "ACME-ServerAuth"
    adcs_ca_name: str = "CONTOSO-CA01-CA"
    # Optional PEM bundle to verify the ADCS /certsrv/ TLS cert (private CA).
    # None/blank -> OS trust store (the gMSA host's local roots).
    adcs_ca_bundle: str | None = None
    # WI-020: assumed CA Web Enrollment UI locale. "en" (default) enables
    # English-string disposition heuristics. A non-"en" locale suppresses
    # those heuristics and relies on locale-independent signals (ReqID,
    # certnew.cer URL) only — failing loudly if none match.
    adcs_locale: str = "en"
    # Per socket operation and one monotonic ceiling across the complete
    # certfnsh/certificate/chain sequence. The latter prevents a peer from
    # extending four individually-valid responses indefinitely by trickling.
    adcs_enrollment_timeout_seconds: float = Field(default=30.0, gt=0)
    adcs_enrollment_total_timeout_seconds: float = Field(default=120.0, gt=0)
    # Dedicated enrollment executor and admission ceiling. ADCS work must never
    # consume the framework's shared worker pool, and ThreadPoolExecutor's own
    # queue is unbounded, so both running and admitted work are bounded.
    adcs_enrollment_max_workers: int = Field(default=4, ge=1)
    adcs_enrollment_max_pending: int = Field(default=32, ge=1)

    # --- Dev/CI escape hatch -------------------------------------------------
    # Off by default. The entrypoint refuses to start on a non-Windows platform
    # unless this is set, because the fake ADCS legs otherwise get selected
    # silently and the RA looks healthy while issuing nothing real.
    allow_fake_adcs_backends: bool = False

    # --- ACME server surface -------------------------------------------------
    base_url: str = "http://localhost:8000"
    terms_of_service: str = ""

    # --- TLS termination (optional) ------------------------------------------
    # When both are set, uvicorn terminates TLS directly. This is the
    # scheduled-task / gMSA deployment shape, where there is no IIS reverse
    # proxy in front. Leave both unset to serve plain HTTP (loopback-only lab
    # use, e.g. the enrollment spike with a local client).
    tls_certfile: Path | None = None
    tls_keyfile: Path | None = None

    # --- Bind address (decoupled from base_url for reverse-proxy hosting) -----
    # Behind IIS/HttpPlatformHandler (or any reverse proxy) the app binds to a
    # loopback port the proxy assigns, while base_url stays the PUBLIC URL used
    # to construct ACME directory / JWS-bound URLs. Empty/None => derive from
    # base_url (direct-serve / loopback lab use).
    bind_host: str = ""
    bind_port: int | None = None
    # When fronted by a TLS-terminating reverse proxy, trust its forwarded
    # headers so the JWS full-URL binding (threat-model §4.D) sees the public
    # scheme/host. forwarded_allow_ips bounds which proxy IPs may set them.
    trust_proxy: bool = False
    forwarded_allow_ips: str = "127.0.0.1"

    # --- SAN scope per account (kid → allowed DNS glob patterns) -------------
    san_scopes: dict[str, SANScope] = {}

    # --- Storage -------------------------------------------------------------
    db_path: Path = Path("acme_ra.db")
    # ACME order/authz lifetime (RFC 8555 §7.1.4). Orders must not be born
    # expired or well-behaved clients reject them immediately.
    order_expiry_seconds: int = 3600

    # --- DoS caps (threat-model §4.G) ----------------------------------------
    # Maximum identifiers per order (bounds per-request work and DB growth)
    # In this implementation, 1 identifier = 1 authorization, so this caps both.
    max_identifiers_per_order: int = 50
    # Maximum CSR body size in bytes (bounds memory + parsing work)
    max_csr_size_bytes: int = 8192
    # Maximum complete flattened-JWS request body.  This is enforced while
    # streaming, before JSON/base64 decoding, so an unauthenticated peer cannot
    # make the worker buffer an arbitrarily large body.
    max_jws_body_size_bytes: int = 65536
    # Maximum body on the token-gated admin routes. Enforced the same way, and
    # present for the same reason: the confirmation callback carries one boolean
    # and had no bound at all, so a holder of the scoped confirm credential
    # could make the single RA process buffer arbitrarily large bodies
    # (2026-08-17 F2). Generous for its purpose — the real body is ~60 bytes.
    max_admin_body_size_bytes: int = 4096

    # --- In-app rate limiting (WI-016) --------------------------------------
    # Per-account (per-kid) order creation ceiling per rolling window.
    # 0 = disabled (rely on reverse-proxy only). Defense-in-depth: bounds a
    # leaked EAB credential's cert flood even without a correctly-configured
    # reverse proxy.
    rate_limit_orders_per_window: int = 50
    # Rolling window duration in seconds.
    rate_limit_window_seconds: int = 3600
    # Global backstop: max orders across ALL accounts per window. 0 = disabled.
    rate_limit_global_per_window: int = 0
    # Per-kid overrides: {kid: limit}. If a kid is not listed, the default
    # rate_limit_orders_per_window applies.
    rate_limit_overrides: dict[str, int] = {}
    # Per-kid ceiling on SUCCESSFUL account-key rollovers per rolling window
    # (14a / daybreak 2026-08-17 F1). keyChange was the one authenticated
    # transition with no rate, quota or cardinality check: a valid — or stolen —
    # account key could chain rotations indefinitely, each one a non-coalesced
    # audit row. Retention bounds the storage consequence; this bounds the
    # action. Shares rate_limit_window_seconds with the order limiter, and is
    # keyed per EAB kid for the same reason: a leaked EAB credential must not
    # be able to spread rotations across freshly minted account keys.
    # 0 = disabled. The default is far above legitimate use — rollover is a
    # rare operation, not a per-renewal one.
    rate_limit_key_changes_per_window: int = Field(default=5, ge=0)

    # --- Unauthenticated nonce ceiling ---------------------------------------
    # /acme/new-nonce is unauthenticated and each call is a SQLite write, so a
    # flood contends for the single writer with the issuance path. This is an
    # in-process token bucket applied BEFORE the write. 0 = disabled (rely on
    # the reverse proxy only). Defaults are far above any legitimate ACME
    # client's needs: a renewal issues a handful of nonces, not hundreds.
    nonce_rate_limit_per_second: float = 20.0
    nonce_rate_limit_burst: int = 100

    # --- Audit durability ----------------------------------------------------
    # The default jsonl sink writes next to the database, so a host compromise
    # — the adversary the threat model calls load-bearing (§4.A) — destroys the
    # audit table and its only mirror together. Set this in production to
    # refuse startup unless audit events leave the box. The default sink that
    # satisfies it is authenticated HTTPS HEC, which both proves delivery and
    # authenticates the collector.
    audit_offbox_required: bool = False

    # TCP syslog satisfies what ``audit_offbox_required`` actually asserts --
    # that the trail leaves the box and that delivery is demonstrable -- but it
    # authenticates nothing and protects nothing in transit, and this codebase
    # has no syslog-over-TLS transport to offer instead. Requiring HEC outright
    # therefore strands every estate whose SIEM is reached by a syslog relay,
    # and the realistic response to a refused start is to turn
    # ``audit_offbox_required`` off entirely -- which is strictly worse, because
    # it drops the off-box requirement rather than just the transport
    # strictness.
    #
    # So the strictness stays the default and the weaker posture is available
    # by explicit acknowledgement, the same shape as ``-AllowInsecureUrl`` and
    # ``-AllowUntrustedScriptPath``: you have to say it, it warns on every
    # start, and it is recorded in the audit trail it weakens. UDP is NOT
    # reachable this way -- that refusal is about whether "required" can mean
    # anything at all, not about transport security.
    audit_offbox_allow_unauthenticated_syslog: bool = False

    # Coalescing window for account-creation denial audit rows, in seconds
    # (second daybreak rescan F4 / the standing WI-014). A peer that passes the
    # network allowlist needs no account to make the RA write one durable SQLite
    # row plus one JSONL line per rejected newAccount, which is unbounded growth
    # on an issuance host's disk.
    #
    # Inside a window, repeats of the same denial reason update the row that is
    # already on disk — bumping an exact counter — instead of adding new ones,
    # so durable growth becomes a function of time rather than of the
    # attacker's request rate. Nothing is deleted and no attempt goes
    # uncounted; see audit_coalesce for why that distinction is the whole
    # point. Set to 0 to write one row per denial, as before this existed.
    audit_denial_coalesce_window_seconds: int = Field(default=60, ge=0)

    # How long audit rows are kept, in days. 0 (the default) keeps everything,
    # which is the behaviour that existed before retention was configurable.
    #
    # When set, it is validated at startup against a floor of "longest
    # certificate validity this RA has actually issued, plus a fixed grace
    # period" — retaining for less than a certificate's own lifetime means a
    # certificate can be valid and servable while the record of how it was
    # issued has been deleted. Startup is refused below that floor rather than
    # warned about; see audit_retention.
    #
    # Setting this alone does not delete anything: it declares the policy and
    # makes the footprint report meaningful. Deletion additionally requires
    # audit_prune_enabled AND audit_offbox_required AND a live off-box delivery
    # probe at sweep time.
    audit_retention_days: int = Field(default=0, ge=0)

    # Reserved for a future acknowledged-archive retention path. Production
    # startup currently refuses True: the library sweep has no production
    # caller, and a generic SIEM health probe is not proof that each candidate
    # row reached off-box storage. Leaving the field present makes old configs
    # fail loudly rather than silently ignoring an operator's pruning policy.
    audit_prune_enabled: bool = False

    # Warn when the local audit footprint (database + JSONL mirror) exceeds this
    # many MiB. 0 disables the warning. This is the half that local-only
    # deployments rely on: they never prune, so measuring is the whole control.
    # The default is generous against measured growth — a few GiB per 180 days
    # even under sustained denial flooding — so crossing it means something has
    # changed rather than that the RA is busy.
    audit_store_warn_mib: int = Field(default=1024, ge=0)

    # Rotate the JSONL audit mirror at this size, keeping audit_jsonl_keep
    # files. 0 disables rotation (append forever, as before). The mirror is
    # local, so rotation is capacity management on a copy — the durable trail is
    # the SQLite table and, when configured, the off-box sink.
    audit_jsonl_max_mib: int = Field(default=256, ge=0)
    audit_jsonl_keep: int = Field(default=4, ge=0)

    # --- SIEM / audit emission -----------------------------------------------
    # Auditing every issuance is mandatory (hard rule). There is no toggle.
    # The default sink is JSON-lines next to the database; syslog and Splunk
    # HEC are optional operator-configured targets.
    siem_sink: Literal["jsonl", "syslog", "hec"] = "jsonl"
    siem_jsonl_path: Path | None = None
    siem_syslog_host: str = ""
    siem_syslog_port: int = 514
    siem_syslog_proto: Literal["udp", "tcp"] = "udp"
    # Seconds a TCP syslog send may block before being abandoned. A stalled
    # receiver would otherwise park the sender indefinitely; see SiemEmitter.
    siem_syslog_timeout_seconds: float = Field(default=5.0, gt=0)
    siem_hec_url: str = ""
    siem_hec_token: SecretStr = Field(default_factory=lambda: SecretStr(""))
    siem_hec_index: str = ""
    siem_hec_sourcetype: str = "acme-adcs-ra"
    # Bound the in-memory HEC delivery queue. A slow or unreachable HEC
    # endpoint must not let request-driven audit events accumulate without
    # limit on an issuance-path host; beyond this depth events are dropped
    # from the HEC sink (never from the local audit table) and counted.
    # Must be >= 1. At 0 or below, `_hec_inflight >= hec_queue_max` is already
    # true at startup with nothing in flight, so EVERY event is dropped — while
    # the emitter still reports itself enabled, so the audit_offbox_required
    # gate passes and the operator believes events are leaving the host. That
    # is the exact failure the gate was added to prevent, reachable by a typo.
    siem_hec_queue_max: int = Field(default=1000, ge=1)

    # Admin API token for maintenance endpoints (e.g., nonce cleanup)
    admin_token: SecretStr = Field(default_factory=lambda: SecretStr(""))

    # Refuse to reclaim an order that may still be enrolling. The reclaim
    # endpoint's only machine check is "no certificate row", which is also true
    # mid-flight, so reclaiming a live enrollment causes double issuance. The
    # default is twice the enrollment leg's own 30s timeout: past that, an
    # enrollment cannot still be in progress.
    reclaim_minimum_processing_age_seconds: int = 60

    # --- CA-side revocation confirmation (WI-024 callback) -------------------
    # Confirming that the CA actually revoked a serial is a *different*
    # authority from general maintenance: it asserts an external security event
    # the RA cannot see. Sharing the maintenance token meant any token holder
    # could drop a still-valid certificate off the retry queue and write a
    # success audit for a revocation that never happened. The confirm endpoint
    # therefore requires this dedicated credential and refuses the admin token;
    # with it unset the endpoint is disabled (fail closed).
    revocation_confirm_token: SecretStr = Field(default_factory=lambda: SecretStr(""))
    # Optional independent proof. The RA holds no CA rights, but a CRL is
    # published, signed by the CA, and readable by anyone — so fetching it is
    # the one check available to the RA that does NOT depend on the calling
    # agent's honesty. When set, a confirmation is verified against the CRL
    # and the audit records `verification="crl-verified"` rather than
    # `"agent-asserted"`.
    revocation_confirm_crl_url: str = ""
    # Fail closed: refuse to confirm at all unless the CRL proves the serial is
    # revoked. Requires revocation_confirm_crl_url.
    revocation_confirm_require_crl_evidence: bool = False
    # Bound the CRL fetch so a slow/hostile endpoint cannot pin a worker.
    revocation_confirm_crl_timeout_seconds: float = 10.0
    revocation_confirm_crl_max_bytes: int = 10 * 1024 * 1024
    # Wall-clock ceiling on the whole retrieval. The timeout above is per-read
    # (that is all `requests` offers), so a server trickling one byte before
    # each read timeout never trips it and holds the worker indefinitely. This
    # is the bound that actually terminates such a transfer.
    revocation_confirm_crl_total_timeout_seconds: float = 30.0
    # Size of the dedicated CRL-evidence thread pool. Deliberately small and
    # deliberately NOT the shared pool that runs ADCS enrollment: a stalled CRL
    # host may exhaust this pool without touching the issuance path.
    revocation_confirm_crl_max_workers: int = 2
    # Admission ceiling on distinct CRL retrievals in progress. max_workers
    # bounds what RUNS; the executor's work queue is unbounded and every waiting
    # caller also pins a suspended request, so without this a stream of distinct
    # serials grows memory without limit. Past the ceiling the confirm endpoint
    # sheds with 429 + Retry-After rather than queueing — the serial stays
    # pending, so the next sync sweep picks it up.
    revocation_confirm_crl_max_pending: int = 32
    # An enforced freshness check on the CA's publication pipeline. Treat a
    # refusal as a liveness alarm; the monotonic watermark below independently
    # rejects evidence older than a CRL already acted on for the issuing CA.
    # Set this ceiling above the observed maximum served age with margin,
    # measured by scripts/sample_crl_age.py across publication cycles.
    # The published validity window and maximum healthy served age differ
    # when publication overlaps. Earlier claims that no CA could have a useful
    # age ceiling conflated those quantities (WI-052, UNFILED item 24).
    revocation_confirm_crl_max_age_seconds: int = 7 * 24 * 3600

    # Refuse a CRL older than the newest one already acted on for the same
    # issuing CA (UNFILED item 23). This comparison does not depend on the
    # age ceiling: it uses the CA's increasing CRL Number (or thisUpdate when
    # absent). A first-seen issuer/key has no prior watermark to compare with.
    #
    # The threat it closes is narrow and real. A stale CRL that *lacks* a serial
    # already fails closed, so age never protected the "was it really revoked?"
    # direction. The only wrong-*accept* an old CRL can produce is a hold→unhold
    # replay: a certificate revoked with reason 6 and later released with reason
    # 8 (`removeFromCRL`) still appears revoked on the older document.
    #
    # Set False in an estate whose CDP replicas are known to lag: the watermark
    # is still recorded and the regression still reaches the audit trail, so the
    # measurement survives without the refusal.
    revocation_confirm_crl_require_monotonic: bool = True
    # Ceiling on concurrently-served requests when the RA runs Uvicorn directly
    # (2026-08-19 F3, CWE-400). Behind IIS the proxy imposes its own limit, but
    # the direct-TLS topology is supported and had none: every slow client got a
    # task, without bound. Uvicorn sheds past this with 503 rather than
    # accumulating, which is the fail-closed direction for an issuance host.
    server_max_concurrency: int = 256

    # Follow HTTP redirects when fetching the CRL. **Off by default** (2026-08-18
    # rescan F2). A `Location` is chosen by whoever answers the configured CDP,
    # so every redirect is attacker-influenced input, and a CDP that redirects at
    # all is unusual — the default therefore removes the hop rather than trying
    # to police it. When enabled, a hop must keep the same host and port (only an
    # http:80 → https:443 upgrade is allowed) and the host must still resolve to
    # the address set seen at the start of the retrieval. If a deployment's CDP
    # genuinely redirects, prefer pointing this at the final URL; enable this only
    # when that is not possible.
    revocation_confirm_crl_follow_redirects: bool = False

    # --- Credential strength -------------------------------------------------
    # EAB MAC keys and the admin token had no strength validation at all: a
    # one-character admin token was accepted, and an EAB entry whose mac_key
    # decoded to zero bytes was treated as a *present* key — so anyone who knew
    # the kid could forge the binding with an empty HMAC key. Both are enforced
    # at config load, which is the only place that sees them before they become
    # load-bearing. Set this to True ONLY for a lab or CI fixture; production
    # deployments must leave it False.
    allow_weak_credentials: bool = False

    @model_validator(mode="after")
    def _audit_pruning_is_not_available(self) -> RAConfig:
        if self.audit_prune_enabled:
            raise ValueError(
                "audit_prune_enabled is not available: the current SIEM path has no "
                "per-row delivery acknowledgement, so deleting local audit rows could "
                "destroy the only copy. Keep it false; audit_retention_days still "
                "enforces the retention floor and audit footprint reporting remains active."
            )
        return self

    @model_validator(mode="after")
    def _base_url_is_a_bare_origin(self) -> RAConfig:
        """`base_url` must be a bare origin, and HTTPS off the loopback.

        2026-08-19, additional improvement. Every ACME URL the RA hands out is
        built from this value, and the JWS `url` check compares against it, so a
        malformed one is not cosmetic: a path or query component silently
        produces directory/order URLs the client then binds its signatures to,
        and a plaintext origin publishes an issuance API over HTTP.

        Loopback stays permissive — the committed default is
        `http://localhost:8000` and the lab/dev flows depend on it — but any
        other host must be HTTPS. This is a configuration guard, not a claim
        about an attacker-controlled path.
        """
        from urllib.parse import urlsplit

        parts = urlsplit(self.base_url)
        if parts.scheme not in ("http", "https"):
            raise ValueError(
                f"base_url must be http or https, got {parts.scheme!r}: {self.base_url}"
            )
        if not parts.netloc:
            raise ValueError(f"base_url has no host: {self.base_url}")
        # A trailing slash is the only path allowed; anything else changes every
        # URL derived from it.
        if parts.path not in ("", "/"):
            raise ValueError(
                "base_url must be a bare origin with no path component "
                f"(got path {parts.path!r} in {self.base_url}). Every ACME URL "
                "is derived from this value."
            )
        if parts.query or parts.fragment:
            raise ValueError(
                f"base_url must carry no query or fragment: {self.base_url}"
            )
        # The plaintext-origin check WARNS rather than refuses, deliberately.
        # A structural defect (path/query/fragment) corrupts every URL derived
        # from this value and is always wrong, so those raise. A plaintext
        # scheme is a deployment mistake this cannot distinguish from a
        # deliberate one: the whole test suite legitimately runs on
        # `http://testserver`, and an operator terminating TLS elsewhere may
        # have reasons the RA cannot see. Loud at startup, not fatal.
        host = (parts.hostname or "").lower()
        is_loopback = host in ("localhost", "127.0.0.1", "::1", "testserver")
        if parts.scheme != "https" and not is_loopback:
            logger.warning(
                "base_url %s is not https. The RA publishes an issuance API and "
                "every ACME URL it hands out will be plaintext. Set "
                "ACME_RA_BASE_URL to the public https origin unless TLS is "
                "terminated in front of this process.",
                self.base_url,
            )
        return self

    @model_validator(mode="after")
    def _no_duplicate_eab_kids(self) -> RAConfig:
        """Duplicate kids would silently overwrite EAB credentials — reject them."""
        seen: set[str] = set()
        for entry in self.eab_allowlist:
            if entry.kid in seen:
                raise ValueError(f"duplicate EAB kid: {entry.kid}")
            seen.add(entry.kid)
        return self

    @model_validator(mode="after")
    def _credentials_are_strong(self) -> RAConfig:
        """Reject empty/short EAB MAC keys and admin tokens at load time.

        Fails closed and loudly at startup rather than silently accepting a
        credential that cannot carry the authentication weight placed on it.
        """
        if self.allow_weak_credentials:
            return self

        problems: list[str] = []

        for entry in self.eab_allowlist:
            kid = entry.kid
            if not kid.strip() or kid != kid.strip():
                problems.append(
                    f"EAB kid {kid!r} must be non-empty and free of surrounding whitespace"
                )
            try:
                key_bytes = _base64url_decode(entry.mac_key.get_secret_value())
            except ValueError:
                # binascii.Error (bad padding/alphabet) and the non-ASCII
                # ValueError both subclass ValueError.
                problems.append(f"EAB mac_key for kid {kid!r} is not valid base64url")
                continue
            if len(key_bytes) < MIN_EAB_MAC_KEY_BYTES:
                problems.append(
                    f"EAB mac_key for kid {kid!r} decodes to {len(key_bytes)} bytes; "
                    f"at least {MIN_EAB_MAC_KEY_BYTES} are required "
                    f"(generate one with `python scripts/eab.py new`)"
                )

        admin_token = self.admin_token.get_secret_value()
        if admin_token and len(admin_token) < MIN_ADMIN_TOKEN_CHARS:
            problems.append(
                f"admin_token is {len(admin_token)} characters; at least "
                f"{MIN_ADMIN_TOKEN_CHARS} are required"
            )

        confirm_token = self.revocation_confirm_token.get_secret_value()
        if confirm_token and len(confirm_token) < MIN_ADMIN_TOKEN_CHARS:
            problems.append(
                f"revocation_confirm_token is {len(confirm_token)} characters; at "
                f"least {MIN_ADMIN_TOKEN_CHARS} are required"
            )

        # Separating the confirm authority is the whole point of having a
        # second credential: the sync agent needs to confirm revocations, and
        # must NOT thereby hold the maintenance authority that can reclaim a
        # processing order or drain the nonce table. Setting both to the same
        # string silently collapses that separation back into one credential
        # while every individual check still passes.
        if admin_token and confirm_token and admin_token == confirm_token:
            problems.append(
                "admin_token and revocation_confirm_token are identical, which "
                "defeats the separation they exist to create — the revocation "
                "agent would hold full maintenance authority. Generate a "
                "distinct confirm token"
            )

        if problems:
            raise ValueError(
                "weak credentials rejected at startup: "
                + "; ".join(problems)
                + ". Set allow_weak_credentials=true ONLY for a lab or CI fixture."
            )
        return self

    @model_validator(mode="after")
    def _offbox_audit_when_required(self) -> RAConfig:
        """Fail startup, loudly, rather than audit only to the box being attacked.

        This is opt-in (``audit_offbox_required``) so lab and CI keep the
        zero-config jsonl sink, but once an operator sets it the RA will not
        start in a posture where the audit trail dies with the host.
        """
        if not self.audit_offbox_required:
            # A security-relevant switch must never be silently inert: an
            # operator who sets the acknowledgement and watches the RA start
            # cannot tell from that whether anything leaves the host.
            if self.audit_offbox_allow_unauthenticated_syslog:
                raise ValueError(
                    "audit_offbox_allow_unauthenticated_syslog is set but "
                    "audit_offbox_required is not, so it weakens nothing and "
                    "guarantees nothing. Set audit_offbox_required=true if you "
                    "want the off-box trail enforced, or drop the "
                    "acknowledgement."
                )
            return self

        if self.siem_sink == "jsonl":
            raise ValueError(
                "audit_offbox_required is set, but siem_sink is 'jsonl', which "
                "writes next to the database: a host compromise takes the audit "
                "table and its only mirror together. Configure the hec sink "
                "(authenticated HTTPS, the default posture) or the syslog sink "
                "over tcp with "
                "audit_offbox_allow_unauthenticated_syslog=true."
            )

        if self.siem_sink == "syslog":
            if self.siem_syslog_proto == "udp":
                raise ValueError(
                    "audit_offbox_required is set with siem_syslog_proto='udp'. "
                    "UDP is fire-and-forget: the socket accepts every datagram "
                    "whether or not a collector exists, so the startup delivery "
                    "probe cannot distinguish a working collector from none at "
                    "all, and 'required' would mean nothing. This is not about "
                    "transport security and the acknowledgement flag does NOT "
                    "reach it. Set siem_syslog_proto='tcp' (proves a live "
                    "transport) or use the hec sink (proves receipt)."
                )
            if not self.audit_offbox_allow_unauthenticated_syslog:
                raise ValueError(
                    "audit_offbox_required is set with the syslog sink. TCP "
                    "syslog does prove a live transport, but it does not "
                    "authenticate the collector and does not protect events in "
                    "transit -- an attacker positioned on the path can read the "
                    "trail or feed the SIEM forged issuance events. Prefer the "
                    "hec sink (authenticated HTTPS). If your SIEM is reached by "
                    "a syslog relay and you accept that trade, set "
                    "audit_offbox_allow_unauthenticated_syslog=true: it is "
                    "logged as a warning on every start and recorded in the "
                    "audit trail."
                )
            return self

        hec_url = urlsplit(self.siem_hec_url)
        if (
            hec_url.scheme != "https"
            or hec_url.hostname is None
            or hec_url.username is not None
            or hec_url.password is not None
            or not self.siem_hec_token.get_secret_value()
        ):
            raise ValueError(
                "audit_offbox_required needs an authenticated HTTPS HEC "
                "sink: configure an https siem_hec_url without embedded "
                "credentials and a non-empty siem_hec_token"
            )
        return self

    @model_validator(mode="after")
    def _crl_evidence_is_obtainable(self) -> RAConfig:
        """Requiring CRL evidence without a CRL URL would wedge every confirm."""
        if (
            self.revocation_confirm_require_crl_evidence
            and not self.revocation_confirm_crl_url
        ):
            raise ValueError(
                "revocation_confirm_require_crl_evidence is set but "
                "revocation_confirm_crl_url is empty: the RA would have no way "
                "to obtain the evidence it is required to check."
            )
        return self

    @model_validator(mode="after")
    def _crl_timeouts_are_coherent(self) -> RAConfig:
        """The total deadline must leave room for at least one read.

        A total below the per-read timeout would cancel a perfectly healthy
        CRL fetch mid-transfer, which withholds evidence — and under
        ``require_crl_evidence`` that wedges confirmation entirely. Catching
        it at load beats discovering it during an incident.
        """
        if self.revocation_confirm_crl_total_timeout_seconds <= 0:
            raise ValueError(
                "revocation_confirm_crl_total_timeout_seconds must be positive"
            )
        if (
            self.adcs_enrollment_total_timeout_seconds
            < self.adcs_enrollment_timeout_seconds
        ):
            raise ValueError(
                "adcs_enrollment_total_timeout_seconds must be at least "
                "adcs_enrollment_timeout_seconds"
            )
        if self.adcs_enrollment_max_pending < self.adcs_enrollment_max_workers:
            raise ValueError(
                "adcs_enrollment_max_pending must be at least "
                "adcs_enrollment_max_workers"
            )
        if self.revocation_confirm_crl_max_workers < 1:
            raise ValueError("revocation_confirm_crl_max_workers must be at least 1")
        if self.revocation_confirm_crl_max_pending < 1:
            raise ValueError("revocation_confirm_crl_max_pending must be at least 1")
        if (
            self.revocation_confirm_crl_max_pending
            < self.revocation_confirm_crl_max_workers
        ):
            raise ValueError(
                "revocation_confirm_crl_max_pending "
                f"({self.revocation_confirm_crl_max_pending}) is below "
                "revocation_confirm_crl_max_workers "
                f"({self.revocation_confirm_crl_max_workers}): the admission "
                "ceiling would shed work the pool has idle capacity for."
            )
        if self.max_admin_body_size_bytes < 1:
            raise ValueError("max_admin_body_size_bytes must be at least 1")
        if (
            self.revocation_confirm_crl_total_timeout_seconds
            < self.revocation_confirm_crl_timeout_seconds
        ):
            raise ValueError(
                "revocation_confirm_crl_total_timeout_seconds "
                f"({self.revocation_confirm_crl_total_timeout_seconds}) is below "
                "revocation_confirm_crl_timeout_seconds "
                f"({self.revocation_confirm_crl_timeout_seconds}): the total "
                "deadline would abort a healthy CRL fetch before its first read "
                "could even time out."
            )
        return self

    @model_validator(mode="after")
    def _tls_cert_key_paired(self) -> RAConfig:
        """TLS needs both halves or neither — a lone cert/key is a misconfig
        that would silently fall back to plain HTTP."""
        if bool(self.tls_certfile) != bool(self.tls_keyfile):
            raise ValueError("tls_certfile and tls_keyfile must be set together")
        return self

    def eab_keys_by_kid(self) -> dict[str, str]:
        """Return {kid: mac_key} for fast EAB lookup.

        The mac_key value is the base64url-encoded key as stored in config.
        Use ``eab_key_bytes`` when the raw key bytes are needed (e.g. HMAC).
        """
        return {e.kid: e.mac_key.get_secret_value() for e in self.eab_allowlist}

    def eab_key_bytes(self, kid: str) -> bytes | None:
        """Return the decoded EAB MAC key bytes for a kid, or None if unknown."""
        for entry in self.eab_allowlist:
            if entry.kid == kid:
                return _base64url_decode(entry.mac_key.get_secret_value())
        return None
